# permissions for end users to view grpcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grpc-viewer-role
rules:
- apiGroups:
  - init.add.com
  resources:
  - grpcs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - init.add.com
  resources:
  - grpcs/status
  verbs:
  - get
